#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      CONFIG:
        default: 'MEDIATEK'
        required: true
        type: choice
        options:
          - MEDIATEK
          - ROCKCHIP
          - X86
          - IPQ50XX-WIFI-YES
          - IPQ50XX-WIFI-NO
          - IPQ60XX-WIFI-YES
          - IPQ60XX-WIFI-NO
          - IPQ807X-WIFI-YES
          - IPQ807X-WIFI-NO
          - TEST
      SOURCE:
        default: 'VIKINGYFY/immortalwrt'
        required: true
        type: choice
        options:
          - VIKINGYFY/immortalwrt
          - immortalwrt/immortalwrt
          - LiBwrt/openwrt-6.x
          - qosmio/openwrt-ipq
      BRANCH:
        default: 'main'
        required: true
        type: string
      PACKAGE:
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.CONFIG}}
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{inputs.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
